project:
  type: website
  post-render:
    - cp -r _static _site
    - cp -r data _site

format:
  live-html:
    theme:
      - zypher
    css: styles.css
    toc: true
    resources:
      - _static/data
      - data
    include-in-header: 
      - text: |
          <link rel="shortcut icon" href="/_static/favicon.svg" type="image/x-icon">
    include-after-body:
      - text: |
          <script src="/_static/papaparse.min.js"></script>
          <script src="/_static/progress-continue.js"></script>
          <script src="/_static/restore-progress.js"></script>

author:
  name: Beau B. Bruce, MD, PhD
  affiliation: Emory University
  email: bbbruce@emory.edu

engine: knitr

filters:
  - webr-adm-ext

metadata-files:
  - _website.yml
