project:
  type: website

format:
  live-html:
    theme:
      - zypher
    css: styles.css
    toc: true

author:
  name: Beau B. Bruce, MD, PhD
  affiliation: Emory University
  email: bbbruce@emory.edu

engine: knitr

filters:
  - webr-adm-ext

metadata-files:
  - _website.yml
