project:
  type: website
  post-render:
    - cp _static/canvas_start_assignment.png _site/_static/
    - cp _static/canvas_submission.png _site/_static/

format:
  live-html:
    theme:
      - zypher
    css: styles.css
    toc: true

author:
  name: Beau B. Bruce, MD, PhD
  affiliation: Emory University
  email: bbbruce@emory.edu

engine: knitr

filters:
  - webr-adm-ext

metadata-files:
  - _website.yml
