project:
  type: website
  post-render:
    - cp -r _static _site

format:
  live-html:
    theme:
      - zypher
    css: styles.css
    toc: true
    resources:
      - _static/data
    include-after-body:
      - text: |
          <script src="/_static/progress-continue.js"></script>

author:
  name: Beau B. Bruce, MD, PhD
  affiliation: Emory University
  email: bbbruce@emory.edu

engine: knitr

filters:
  - webr-adm-ext

metadata-files:
  - _website.yml
