---
title: "Exercises"
sidebar: false
---

{{< include ../_static/_shared.qmd >}}

The exercises form the core instructional and evaluative material for the 
course.

1. [Rithmatic](01-Rithmatic.qmd): a basic introduction starring the arithmetic operators [[canvas]](`r .canvas_link("01-Rithmatic")`){.canvas}
2. [Atomic Data Types](02-Atomic-Data-Types.qmd): a deep dive into R's most important basic data types, i.e., numeric, character (strings), and logical (boolean) data types [[canvas]](`r .canvas_link("02-Atomic-Data-Types")`){.canvas} 
3. [Rcel, Part 1](03-Rcel1.qmd): an introduction to two of R's composite data structures, i.e., `vector` and `factor` [[canvas]](`r .canvas_link("03-Rcel1")`){.canvas}
4. [Rcel, Part 2](04-Rcel2.qmd): a continuation of our exploration of key R composite data structures, focusing on `list` and `data.frame` [[canvas]](`r .canvas_link("04-Rcel2")`){.canvas}
5. [Functions](05-Functions.qmd): a deep dive into R functions, including function arguments and return values [[canvas]](`r .canvas_link("05-Functions")`){.canvas}
6. [Branching Out & Feeling Loopy](06-Branch-Loop.qmd): an introduction to control structures in R, including `if`{.r} statements and `for`{.r} loops [[canvas]](`r .canvas_link("06-Branch-Loop")`){.canvas}
7. [Food Prep](07-Food-Prep.qmd): review of many concepts around data selection and indexing with some new techniques to help you transform, merge, and sort data [[canvas]](`r .canvas_link("07-Food-Prep")`){.canvas}
8. [Reading & Writing Files](07a-Read-Write-Files.qmd): an introduction to reading and writing files in R, including CSV, Excel, and RDS files
9. [Base Graphics](08-Base-Graphics.qmd): an introduction to R's base graphics system [[canvas]](`r .canvas_link("08-Base-Graphics")`){.canvas}
10. [Reproducible Research](09-Reproducible-Research.qmd): learn to make reproducible research documents including
formatted tables using Quarto [[canvas]](`r .canvas_link("09-Reproducible-Research")`){.canvas}
    * [Basic Table Example](09a-Basic-Table-Example.qmd)
    * [Advanced Table Example](09b-Advanced-Table-Example.qmd)
    * [Reproducible Research Exercise](09c-Reproducible-Research-Exercise.qmd) [[canvas]](`r .canvas_link("09-Reproducible-Research")`){.canvas}
11. [Grammar of Graphics](10-Grammar-of-Graphics.qmd): an introduction to data visualization in R using the `ggplot2` package and the grammar of graphics framework [[canvas]](`r .canvas_link("10-Grammar-of-Graphics")`){.canvas}